# Generated by Django 4.2.6 on 2023-10-16 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='product_code',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='producttypedata',
            name='product_type_code',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shopdata',
            name='shop_code',
            field=models.CharField(max_length=8, null=True, unique=True),
        ),
    ]
