# Generated by Django 4.2.6 on 2023-10-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdata',
            name='product_desc',
            field=models.TextField(default='-'),
        ),
    ]
