# Generated by Django 4.2.6 on 2023-10-13 02:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerdata',
            name='customer_name',
        ),
    ]
